// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC556hAp2AIeRsofV6MH2VMtmEhSgaWgJI',
    appId: '1:506568949646:web:bcf75295223aad80692edf',
    messagingSenderId: '506568949646',
    projectId: 'wasftk-911',
    authDomain: 'wasftk-911.firebaseapp.com',
    storageBucket: 'wasftk-911.firebasestorage.app',
    measurementId: 'G-0MMM6JXL17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZSqoCArVZVBY-z_cFCVq3bHyVoX2G0v8',
    appId: '1:506568949646:android:c12d55d4aa2b1513692edf',
    messagingSenderId: '506568949646',
    projectId: 'wasftk-911',
    storageBucket: 'wasftk-911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFwdqzV3SncuzSbsbAwYEao8642rcIKN0',
    appId: '1:506568949646:ios:1110170a4a534e95692edf',
    messagingSenderId: '506568949646',
    projectId: 'wasftk-911',
    storageBucket: 'wasftk-911.firebasestorage.app',
    iosBundleId: 'com.example.wasftk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFwdqzV3SncuzSbsbAwYEao8642rcIKN0',
    appId: '1:506568949646:ios:1110170a4a534e95692edf',
    messagingSenderId: '506568949646',
    projectId: 'wasftk-911',
    storageBucket: 'wasftk-911.firebasestorage.app',
    iosBundleId: 'com.example.wasftk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC556hAp2AIeRsofV6MH2VMtmEhSgaWgJI',
    appId: '1:506568949646:web:589c642ee0e7cb22692edf',
    messagingSenderId: '506568949646',
    projectId: 'wasftk-911',
    authDomain: 'wasftk-911.firebaseapp.com',
    storageBucket: 'wasftk-911.firebasestorage.app',
    measurementId: 'G-D382BX6C32',
  );
}
